version: "3.7"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    volumes:
      # Attach .../Curse/Minecraft/Instances for use at /instances
      - ./Instances:/instances:ro
      # Attach /data as usual
      - ./ServerData:/data
    environment:
      EULA: "TRUE"
      # Modpacks generally need more memory, so let's give at 2 GB
      MEMORY: 2G
      # Use new CURSE_INSTANCE type
      TYPE: CURSE_INSTANCE
      # Reference directory of or full path to minecraftinstance.json
      CURSE_INSTANCE_JSON: /instances/FTB Presents SkyFactory 3
